language: objective-c
os: osx
osx_image: xcode7.2

xcode_project: Colors.swift/Colors.swift.xcodeproj
xcode_scheme: Colors.swift

script:
- set -o pipefail && xcodebuild -project Colors.swift/Colors.swift.xcodeproj -scheme Colors.swift clean build test | xcpretty
